package com.cs115.rex;

import android.content.Context;
import android.database.Cursor;
import android.os.Bundle;
import android.support.v4.app.ListFragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;
import android.widget.SimpleCursorAdapter;

/**
 * The list fragment that handles the list of search results. The accompanying view
 * displays the list of search results.
 */
public class ResultsFragment extends ListFragment {
    public static final String SEARCH_RESULTS = "search_results";
    public static final String SEARCH_NAME = "search_name";
    protected String searchName;
    protected String[] searchResults;

    /**
     * The interface to facilitate click listener between top-level activity and activities that it calls.
     */
    interface Listener {
        /**
         * Interface method to facilitate click listener in path from search to results to detail page.
         * @param id Food table item id corresponding to list item that user has clicked
         * @return void
         */
        void onClickResult(long id);
    }

    private Listener listener;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            //Log.d("DebugLog: ", "ResultsFragment - Value: " + getArguments().getStringArray(SEARCH_RESULTS)[0]);
            searchResults = getArguments().getStringArray(SEARCH_RESULTS);
            searchName = getArguments().getString(SEARCH_NAME);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        String[] results = searchResults;

        Cursor cursor = RexDatabaseUtilities.getSelectedFoodList(getActivity(), searchName);

        SimpleCursorAdapter adapter = new SimpleCursorAdapter(getActivity(),
                android.R.layout.simple_list_item_1,
                cursor,
                new String[]{"NAME"},
                new int[]{android.R.id.text1},
                0);
        setListAdapter(adapter);

        return super.onCreateView(inflater, container, savedInstanceState);
    }

    /**
     * Instantiates a ResultsFragment with saved arguments corresponding to the parameters.
     * @param searchName the search term input by the user
     * @param searchResults the array of results generated by the search
     * @return ResultsFragment with arguments corresponding to parameters
     */
    public static ResultsFragment newInstance(String[] searchResults, String searchName){
        ResultsFragment resultsFragment = new ResultsFragment();

        Bundle bundle = new Bundle();
        bundle.putStringArray(SEARCH_RESULTS, searchResults);
        bundle.putString(SEARCH_NAME, searchName);
        resultsFragment.setArguments(bundle);
        return resultsFragment;
    }

    /**
     * Sets local variables from a different activity or fragment.
     * @param searchName the search term input by the user
     * @param searchResults the array of results generated by the search
     * @return void
     */
    public void setDataFromActivity(String[] searchResults, String searchName){
        this.searchResults = searchResults;
        this.searchName = searchName;
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        this.listener = (Listener) context;

    }

    //@Override
    public void onListItemClick(ListView listView, View itemView, int position, long id) {
        if (listener != null) {
            listener.onClickResult(id);
        }
    }
}
